"""initial migration

Revision ID: 7818da359723
Revises: 
Create Date: 2024-09-19 03:09:13.433095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7818da359723'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adopted_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firt_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_names'), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=225), nullable=False),
    sa.Column('middle', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=225), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_admitted', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genotype', sa.String(length=100), nullable=True),
    sa.Column('blood_group', sa.String(length=100), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=225), nullable=False),
    sa.Column('last_name', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('lga', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_names'), nullable=False),
    sa.Column('phone_num', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('nin', sa.Integer(), nullable=False),
    sa.Column('marital_status', sa.String(length=20), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nin'),
    sa.UniqueConstraint('phone_num')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_email'), ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_names'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('phone_num', sa.String(length=11), nullable=False),
    sa.Column('nin', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nin')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('adoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('adoptive_parent_name', sa.String(length=255), nullable=False),
    sa.Column('adopter_id', sa.Integer(), nullable=True),
    sa.Column('adoption_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['adopter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adoption')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_email'))

    op.drop_table('staff')
    op.drop_table('medical_record')
    op.drop_table('roles')
    op.drop_table('child')
    op.drop_table('adopted_child')
    # ### end Alembic commands ###
